### ISSUE TITLE
Invalid file paths prevent cloning repo.

### ISSUE THREAD

**Issue by JosiahBradley** [bbkane/trinitylist#1]
The following files appear to have unprintable characters, they even display as ? on github web. This prevents github desktop app and github cli from checking out these files (at least on Windows 11, will try Linux later)

`  (use "git restore --staged <file>..." to unstage)
        deleted:    d0?_data_conversion.go
        deleted:    d0?_text_list.go
        deleted:    d0?_two_way_binding.go`

**Comment by bbkane** [comment]
Haha those are literal question marks. Can the git CLI check them out?

**Comment by bbkane** [comment]
Updated names
